### ISSUE TITLE
Square boxType is pixelated on iPhone 6 Plus

### ISSUE THREAD

**Issue by danie11am** [Boris-Em/BEMCheckBox#14] opened 2016-01-11 15:20 UTC
![img_1545](https://cloud.githubusercontent.com/assets/2687370/12237468/eaa31940-b8d2-11e5-9d92-67cfed8cdca3.PNG)

Only found in iPhone 6 Plus, both simulator and device.

Screenshot was taken from device, lineWidth = 2 (tried 1 as well and looked the same).

Great work btw! Thanks!

**Comment by kevinmmarlow** [comment] 2016-01-18 08:04
I've seen the same thing, but with a 5s running iOS 9.2

**Comment by Boris-Em** [comment] 2016-01-19 02:29
This seems to be a duplicate of #13, and should be fixed with the release of 1.2.0.
Please reopen this bug if not fixed.
Thank to you two for your contribution!

**Closed by Boris-Em** 2016-01-19 02:29 UTC
Labels: duplicate
