### ISSUE TITLE
Using `on` property requires `reload` and loses animation

### ISSUE THREAD

**Issue by danie11am** [Boris-Em/BEMCheckBox#15] opened 2016-01-12 12:29 UTC
If the `on` value is set without calling `reload`, the entire checkbox disappears. It is actually still tappable, and would re-appear when it is tapped to `on`.

Then I tried calling `reload` after changing `on` value. This time the checkbox won't disappear, but the on/off animation will be gone forever in this checkbox instance.

**Comment by Boris-Em** [comment] 2016-01-12 18:40
Hi @danie11am,
Thank you for opening this issue!
What version of **BEMCheckBox** are you currently using?

This is potentially a duplicate of #6.

**Comment by danie11am** [comment] 2016-01-12 23:05
No problem! I'm using 2.1.0.

**Comment by Boris-Em** [comment] 2016-01-19 02:32
Thanks @danie11am, but the latest version of BEMCheckBox is 1.2.0!  
Would you mind checking with this version that the bug still occurs? 
In the meantime I going to close this bug because I strongly suspect it to be fixed with 1.2.0.  
Thank again!

**Closed by Boris-Em** 2016-01-19 02:32 UTC
Labels: bug, question

**Comment by danie11am** [comment] 2016-01-19 03:38
Argh! I'm sorry - I was using 1.1.0. Sure I'll try 1.2.0.

**Comment by danie11am** [comment] 2016-01-19 14:41
Yep it works. No need to call `reload()`. And the "loses animation" bit was probably my mistake, where my "didTapOnCheckbox" would cause a state change, and the `didSet` of my state change set the `checkbox.on`, therefore losing the animation. Fixed that too.

**Comment by Boris-Em** [comment] 2016-01-19 17:40
@danie11am,
Great to hear, thanks for your feedback!
