### ISSUE TITLE
Clipped border

### ISSUE THREAD

**Issue by Emailrus** [Boris-Em/BEMCheckBox#34] opened 2016-09-12 09:59 UTC
It seems, that `BEMPathManager` doesn't take into account `lineWidth`, therefore drawings of the box will be clipped at the bottom by container view and drawings of the checkmark will be slightly skewed downwards

**Comment by Boris-Em** [comment] 2016-09-12 21:29
That definitely seems like a bug. Would you mind giving repro steps and maybe a screenshot illustrating the issue?
Thanks!

**Comment by Emailrus** [comment] 2016-09-13 07:33
If you take your example project, in storyboard you can already see clipped borders. If you tick checkbox "clip subviews" on checkbox view, you will see clipping in running project too. 
It seems my first assumption wasn't entirely correct though: clipping occurs on all sides.

**Comment by Boris-Em** [comment] 2016-10-20 18:30
My guess is that this has to do with the calculation of the path where the line width is not taking into account. Unfortunately I can't think of a fix, without making the checkbox smaller, which will impact current users of the library.

**Comment by Emailrus** [comment] 2016-10-21 08:34
Yeah, guess in that case it might be better to postpone it to something like a 2.0 release

**Comment by Boris-Em** [comment] 2017-02-21 15:25
Closing this as a duplicate of issue #47 which is better documented.

**Closed by Boris-Em** 2017-02-21 15:25 UTC
Labels: bug
